#!/bin/bash

_argStr="$*";
_debugFile="/tmp/DEBUG-automark";
_appName="$(basename "$0")";

1>&2 echo "${_basename}: BEGIN Mark kernel packages as auto installed";
read -r -d '' -a _manualList < <( apt-mark showmanual \
  | grep -E '^linux-([[:alpha:]]+-)+[[:digit:].]+-[^-]+(|-.+)$'
);

{ date
  cat <<_EOF
_argStr     = >${_argStr}<
_manualList = >${_manualList[*]}<
==========================
_EOF
if [ "${#_manualList[@]}" -gt 0 ]; then
  apt-mark auto "${_manualList[@]}" || true;
fi
} >> "${_debugFile}";
1>&2 echo "${_basename}: . END Mark kernel packages as auto installed";
