#! /bin/bash
set -u;

# See https://stackoverflow.com/questions/2683279
#   Run if not sourced
# if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
#   _assignGlobalVarsFn;
#   _runTestFn;
# fi

_cm0EchoFn () { 1>&2 echo -e "$*";  }
## BEGIN _cm0EscapeRxCharsFn {
  # Escape any regex special characters for use in grep -E '...'
  # See https://unix.stackexchange.com/questions/20804
  # shellcheck disable=2016
_cm0EscapeRxCharsFn () {
  if [ "$#" -eq 0 ]; then
    echo '';
    return;
  fi
  printf '%s' "$1" | sed 's/[.[\*^$()+?{|]/\\&/g';
}
## . END _cm0EscapeRxCharsFn }

# Test-harness: Clear and recreate run directory
_t00ClearRunDirFn () {
  if [ -d "${_t00RunDir}" ]; then
    if ! "${_t00rmExe}" -rf "${_t00RunDir}"; then
      _cm0EchoFn 'FAIL: Could not clear run dir';
      return 1;
    fi
  fi

  if ! mkdir -p "${_t00RunDir}"; then
    _cm0EchoFn "FAIL: cannot create ${_t00RunDir}";
    return 1;
  fi
  return 0;
}

# Test-harness: Clear and copy init into run directory
_t00CopyInitDirFn () {
  if [ -d "${_t00RunDir}" ]; then
    if ! "${_t00rmExe}" -rf "${_t00RunDir}"; then
      _cm0EchoFn 'FAIL: Could not clear run dir';
      return 1;
    fi
  fi

  if [ ! -d "${_t00InitDir}" ]; then
    _cm0EchoFn "FAIL: Missing init dir ${_t00InitDir}";
    return 1;
  fi

  if ! cp -a "${_t00InitDir}" "${_t00RunDir}"; then
    _cm0EchoFn "FAIL: Could not copy init dir ${_t00InitDir}";
    return 1;
  fi
  return 0;
}

# Test-harness: Check expect directory
_t00CheckExpectDirFn () {
  mkdir -p "${_t00ExpectDir}";
  if [ ! -d "${_t00ExpectDir}" ]; then
    _cm0EchoFn "FAIL: Missing expect dir ${_t00ExpectDir}";
    return 1;
  fi
  return 0;
}

## BEGIN _t00RunTestScriptsFn {
_t00RunTestScriptsFn () {
  declare _return_int _filter_str _fail_list _unit_count \
    _unit_list _unit_file _unit_basename;

  # Set default return value
  _return_int=0;

  # Build escaped filter string
  [ "$#" -gt 0 ] && _filter_str="$1" || _filter_str='';
  _filter_str="$(_cm0EscapeRxCharsFn "${_filter_str}")";

  # Create unit test list of sorted files
  cd "${_t00BinDir}/unit.d" || exit 201;
  read -r -d '' -a _unit_list < <( 
    find ./ -maxdepth 1 -mindepth 1 | grep -E "^./${_filter_str}" | sort
  );

  # Export bindir for unit tests
  export _t00BinDir="${_t00BinDir}";

  ## Begin Iterate over unit files {
  _fail_list=();
  _unit_count=0;
  for _unit_file in "${_unit_list[@]}"; do
    _unit_basename="$( basename "${_unit_file}" )" || exit 1;

    # Export dirs for use by test script
    _t00ExpectDir="${_t00DataDir}/expect/${_unit_basename}";
    _t00InitDir="${_t00DataDir}/initial/${_unit_basename}";
    _t00RunDir="${_t00DataDir}/run/${_unit_basename}";
    # This is retained for upstream compatibility
    _t00TopDir="${_t00BaseDir}";
    export _t00ExpectDir _t00InitDir _t00RunDir _t00TopDir;

    # Source the file, clearing _runTestFn var first
    unset _runTestFn;

    # shellcheck disable=SC1090
    source "${_unit_file}";

    if [ "$(type -t _runTestFn)" = 'function' ]; then
        _cm0EchoFn "=====> BEGIN : ${_unit_basename}";
      if _runTestFn; then
        _cm0EchoFn "<===== PASS  : ${_unit_basename}\n";
      else
        _cm0EchoFn "<===== FAIL  : ${_unit_basename}\n";
        _fail_list+=( "$_unit_basename" );
      fi
    else
      _cm0EchoFn "<===== FAIL  : ${_unit_basename}: NO _runTestFn exported\n";
      _fail_list+=( "$_unit_basename" );
    fi
    (( _unit_count++ ));

    # Reimport common.source to overwrite any mocks
    # shellcheck disable=SC1090
    # DISABLED from upstream: source "${_t00BinDir}/common.source";
  done;
  ## End Iterate over unit files }

  # Summarize results and return results
  if [ "${_filter_str}" = '' ]; then
    _cm0EchoFn $'\nAll unit tests run...';
  else
    _cm0EchoFn "\nIMPORTANT: Selected tests match |^./${_filter_str}|";
  fi

  if [ "${#_fail_list[@]}" -gt 0 ]; then
    _cm0EchoFn "====== FAIL! ${#_fail_list[@]} of ${_unit_count} tests failed:";
    ( IFS=$'\n'; _cm0EchoFn "${_fail_list[*]}" );
    _return_int=1;
  else
    _cm0EchoFn "====== SUCCESS - all ${_unit_count} tests passed.";
  fi
  _cm0EchoFn;

  return "${_return_int}";
}

## BEGIN _t00MainFn {
_t00MainFn () {
  declare _t00BinName;

  ## Begin Env Setup {
  # Import common
  # USES _cm0EchoFn and _cm0EscapeRxCharsFn
  #
  # shellcheck source=/usr/lib/kfocus-001/lib/common.source
  # DISABLED from upstrea: source "${_t00BinDir}/common.source";
  ## . End Env Setup }

  mkdir -p "${_t00DataDir}" \
    || (cm0EchoFn "Could not create ${_t00DataDir}"; exit 1);

  # Pass optional filter string
  _t00RunTestScriptsFn "${1:-}";
}
## . END _t00MainFn }

export -f _t00ClearRunDirFn _t00CopyInitDirFn _t00CheckExpectDirFn;

_t00BinName="$(readlink -f "$0")" || exit 101;
_t00BinDir="$(dirname "${_t00BinName}")" || exit 101;
_t00BaseDir="$(dirname "${_t00BinDir}")" || exit 101;
# _t00DataDir="${_t00BaseDir}/test-data";
_t00DataDir="${_t00BinDir}/test-data";
_t00rmExe='/bin/rm';

_t00MainFn "$@";
